import { Platform, StyleSheet } from "react-native";

export const mapstyles = StyleSheet.create({
  container: {
    backgroundColor: '#eef2f1',
    flex: 1,
  },
  topPanel: {
    backgroundColor: '#ffffff',
    borderRadius: 8,
    left: 14,
    padding: 12,
    position: 'absolute',
    right: 14,
    shadowColor: '#000000',
    shadowOffset: {width: 0, height: 8},
    shadowOpacity: 0.14,
    shadowRadius: 18,
    top: Platform.OS === 'ios' ? 58 : 18,
  },
  routeInputs: {
    flexDirection: 'row',
    gap: 10,
  },
  routeDots: {
    alignItems: 'center',
    paddingTop: 15,
    width: 16,
  },
  routeDot: {
    borderRadius: 6,
    height: 12,
    width: 12,
  },
  pickupDot: {
    backgroundColor: '#00aa5b',
  },
  destinationDot: {
    backgroundColor: '#111827',
  },
  routeLine: {
    backgroundColor: '#d1d5db',
    flex: 1,
    marginVertical: 4,
    width: 2,
  },
  inputGroup: {
    flex: 1,
    gap: 8,
  },
  input: {
    backgroundColor: '#f3f4f6',
    borderColor: '#e5e7eb',
    borderRadius: 8,
    borderWidth: 1,
    color: '#111827',
    fontSize: 15,
    minHeight: 44,
    paddingHorizontal: 12,
  },
  inputActive: {
    borderColor: '#00aa5b',
  },
  quickActions: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 10,
  },
  currentButton: {
    alignSelf: 'flex-start',
    backgroundColor: '#e8f7ef',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  currentButtonText: {
    color: '#007a43',
    fontSize: 13,
    fontWeight: '700',
  },
  suggestions: {
    borderTopColor: '#eef2f1',
    borderTopWidth: 1,
    marginTop: 10,
    maxHeight: 230,
  },
  suggestionItem: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    paddingVertical: 10,
  },
  placeIcon: {
    alignItems: 'center',
    backgroundColor: '#e8f7ef',
    borderRadius: 8,
    height: 34,
    justifyContent: 'center',
    width: 34,
  },
  placeIconText: {
    color: '#007a43',
    fontWeight: '800',
  },
  placeText: {
    flex: 1,
  },
  placeTitle: {
    color: '#111827',
    fontSize: 14,
    fontWeight: '700',
  },
  placeSubtitle: {
    color: '#6b7280',
    fontSize: 12,
    lineHeight: 17,
    marginTop: 2,
  },
  bottomSheet: {
    backgroundColor: '#ffffff',
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    bottom: 0,
    left: 0,
    maxHeight: '48%',
    padding: 16,
    position: 'absolute',
    right: 0,
    shadowColor: '#000000',
    shadowOffset: {width: 0, height: -8},
    shadowOpacity: 0.12,
    shadowRadius: 18,
  },
  summaryRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  sheetEyebrow: {
    color: '#00aa5b',
    fontSize: 12,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  sheetTitle: {
    color: '#111827',
    fontSize: 22,
    fontWeight: '800',
    marginTop: 2,
  },
  priceBox: {
    alignItems: 'flex-end',
  },
  priceLabel: {
    color: '#6b7280',
    fontSize: 12,
  },
  priceText: {
    color: '#111827',
    fontSize: 17,
    fontWeight: '800',
  },
  metricsRow: {
    backgroundColor: '#f8fafc',
    borderRadius: 8,
    flexDirection: 'row',
    marginTop: 14,
    padding: 10,
  },
  metricItem: {
    flex: 1,
  },
  metricValue: {
    color: '#111827',
    fontSize: 16,
    fontWeight: '800',
  },
  metricLabel: {
    color: '#6b7280',
    fontSize: 12,
    marginTop: 2,
  },
  serviceList: {
    gap: 10,
    marginTop: 14,
  },
  serviceCard: {
    alignItems: 'center',
    borderColor: '#e5e7eb',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'space-between',
    padding: 12,
  },
  serviceActive: {
    backgroundColor: '#effaf4',
    borderColor: '#00aa5b',
  },
  serviceName: {
    color: '#111827',
    fontSize: 15,
    fontWeight: '800',
  },
  serviceDescription: {
    color: '#6b7280',
    fontSize: 12,
    marginTop: 2,
    maxWidth: 210,
  },
  serviceFare: {
    color: '#111827',
    fontSize: 13,
    fontWeight: '800',
  },
  noteInput: {
    backgroundColor: '#f3f4f6',
    borderColor: '#e5e7eb',
    borderRadius: 8,
    borderWidth: 1,
    color: '#111827',
    fontSize: 14,
    marginTop: 14,
    minHeight: 46,
    paddingHorizontal: 12,
  },
  orderButton: {
    alignItems: 'center',
    backgroundColor: '#00aa5b',
    borderRadius: 8,
    justifyContent: 'center',
    marginTop: 14,
    minHeight: 48,
  },
  orderButtonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '800',
  },
  historySection: {
    marginTop: 18,
    paddingBottom: 30,
    
  },
  historyTitle: {
    color: '#111827',
    fontSize: 15,
    fontWeight: '800',
    marginBottom: 8,
  },
  historyItem: {
    borderTopColor: '#eef2f1',
    borderTopWidth: 1,
    paddingVertical: 10,
  },
  historyRoute: {
    color: '#111827',
    fontSize: 13,
    fontWeight: '700',
  },
  historyMeta: {
    color: '#6b7280',
    fontSize: 12,
    marginTop: 3,
  },
});
